### PR TITLE
Followup from python 3 changes.

### PR DESCRIPTION
**Pull request by rygwdn**
- Undo some unnecessary changes
- Fix the ordering of 'produces' and 'consumes'

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/aioTV/django-rest-swagger/pull/16" target="_blank">ReviewNinja

**Comment by npars** [comment]
:star:

**Comment by rtwall** [comment]
:2:

**Comment by mdentremont** [comment]
+1

**Pull request merged**
